{% set name = "vcrpy" %}
{% set version = "1.10.3" %}
{% set sha256 = "b2c76736999d81d5321b94d997e3480ffbde8fe56d918eb2798d0e0545cb9f21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 2

requirements:
  build:
    - python
    - setuptools
    - pyyaml
    - wrapt
    - six >=1.5
    - mock  # [py27]
    - contextlib2  # [py27]

  run:
    - python
    - pyyaml
    - wrapt
    - six >=1.5
    - mock  # [py27]
    - contextlib2  # [py27]

test:
  # Python imports
  imports:
    - vcr
    - vcr.persisters
    - vcr.serializers
    - vcr.stubs

about:
  home: https://github.com/kevin1024/vcrpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Automatically mock your HTTP interactions to simplify and speed up testing'
  dev_url: https://github.com/kevin1024/vcrpy
  doc_url: https://vcrpy.readthedocs.io/

extra:
  recipe-maintainers:
    - dopplershift
